# Generated by Django 2.2.3 on 2020-06-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('template_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('property', models.TextField(null=True)),
                ('js', models.TextField(null=True)),
                ('css', models.TextField(null=True)),
            ],
        ),
    ]
