# Generated by Django 2.2.3 on 2020-06-08 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('layout', '0002_template_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='template',
            name='template_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='template',
            unique_together={('user', 'template_name')},
        ),
    ]
