# Generated by Django 2.2.3 on 2020-06-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0003_auto_20200608_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='html',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='template',
            name='css',
            field=models.TextField(default='g'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='template',
            name='js',
            field=models.TextField(default=('sad', 'sad')),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='template',
            name='property',
            field=models.TextField(),
        ),
    ]
