# Generated by Django 2.2.3 on 2020-06-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0004_auto_20200608_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='css',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='template',
            name='html',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='template',
            name='js',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='template',
            name='property',
            field=models.TextField(default=''),
        ),
    ]
