# Generated by Django 2.2.3 on 2020-06-01 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('template_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('html', models.TextField(null=True)),
                ('js', models.TextField(null=True)),
                ('css', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SideNav',
            fields=[
                ('side_nav', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tab_index', models.IntegerField(null=True)),
                ('slug', models.CharField(default='null', max_length=250)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='report.Templates')),
            ],
        ),
        migrations.CreateModel(
            name='FieldData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.TextField()),
                ('side_nav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.SideNav')),
            ],
        ),
    ]
